### PR TITLE
Fixed issue 459

### PR DESCRIPTION
**Pull request by GuilhermeReda**
Added a conditional statement to only add quotes to key that don't already have them.

### CODE REVIEW

**Comment by im-kulikov** [comment]
travis-ci fail on this lines:
- https://github.com/75team/thinkjs/pull/460/files#diff-55a5d5e9ab2678195c04299e06527bdbR235
- https://github.com/75team/thinkjs/pull/460/files#diff-55a5d5e9ab2678195c04299e06527bdbR237

**Comment by im-kulikov** [comment]
@GuilhermeReda thx for so fast answer 👍

**Comment by GuilhermeReda** [comment]
The problem is.

When you pass only the column name it will work, but if you pass schema.column AS column it will do "schema.column AS column"

Gotta think a way of adding the quotes only on schemas e column names and alias.

**Comment by im-kulikov** [comment]
@GuilhermeReda there is one trouble:

if we pass next code:
```js
yield this.model('some_model')
          .field(['DISTINCT some_field'])
....
```

it will generate:

```sql
SELECT "DISTINCT some_field" FROM "some_model"
```

or i'm wrong?

and if another example:

```js
yield this.model('some_model')
          .field(['some_field '])
....
```
it will generate:

```sql
SELECT "some_field " FROM "some_model"
```

whether wee need to wrap the keys?

**Comment by im-kulikov** [comment]
AppVeyor fails because:
- 0.12:

```
npm ERR! path C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.16.2\package.tgz
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! Error: EPERM, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.16.2\package.tgz'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\lodash\4.16.2\package.tgz']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\lodash\\4.16.2\\package.tgz',
npm ERR!   parent: 'babel-template' 
```
- 4.2 & 5.2:

  2 failing
```
  1) watch_compile compileByTypeScript:
     Error: timeout of 50000ms exceeded
      at null.<anonymous> (C:\projects\thinkjs\node_modules\mocha\lib\runnable.js:139:19)
      at Timer.listOnTimeout (timers.js:92:15)
  2) watch_compile compileByTypeScript, show log:
     Error: timeout of 50000ms exceeded
      at null.<anonymous> (C:\projects\thinkjs\node_modules\mocha\lib\runnable.js:139:19)
      at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by im-kulikov** [comment]
`parseKey` must pass next test-cases:

```js
it('parseKey, empty', function(){
    var instance = new PostgreSQL();
    var data = instance.parseKey();
    assert.equal(data, '')
  });
  it('parseKey', function(){
    var instance = new PostgreSQL();
    var data = instance.parseKey('test');
    assert.equal(data, "\"test\"")
  });
  it('parseKey, has special chars', function(){
    var instance = new PostgreSQL();
    var data = instance.parseKey('te"st');
    assert.equal(data, "\"te\"\"st\"")
  });
  it('parseKey, "table_name"."some_field"', function(){
    var instance = new PostgreSQL();
    var data = instance.parseKey('table_name.some_field');
    assert.equal(data, "\"table_name\".\"some_field\"")
  });
  it('parseKey, DISTINCT "table_name"."some_field"', function(){
    var instance = new PostgreSQL();
    var data = instance.parseKey('DISTINCT table_name.some_field');
    assert.equal(data, "\"table_name\".\"some_field\"")
  });
  it('parseKey, \'"table_name"."some_field"   \' (with spaces)', function(){
    var instance = new PostgreSQL();
    var data = instance.parseKey('DISTINCT table_name.some_field');
    assert.equal(data, "\"table_name\".\"some_field\"")
  });
```
now i tried to write some PostgreSQL tests for this task (#461) and with this fixes it not pass successfully...

**Pull request merged**
