### PR TITLE
fix problems from PR #473

### PR DESCRIPTION
**Pull request by im-kulikov**

### CODE REVIEW

**Comment by im-kulikov** [comment]
@welefen please, take a moment, i'm fix conflicts myself

**Comment by im-kulikov** [comment]
almost complete

**Comment by im-kulikov** [comment]
alt tag

**Comment by im-kulikov** [comment]
@welefen i'm finished and test all

**Comment by im-kulikov** [comment]
one moment, i replaced:
```js
catch(function(err){
console.log(err);
})
```
with:
```js
catch(function(err){ done(err) })
```

it's mocha's style - http://mochajs.org/#asynchronous-code
example

**Comment by welefen** [comment]
Please fix eslint errors

**Comment by im-kulikov** [comment]
@welefen one moment

**Comment by im-kulikov** [comment]
@welefen https://github.com/75team/thinkjs/pull/475 

it's strange, bun when i run `npm run test` it not show this errors (eslint)

**Pull request merged**
